Linters
Rdzaman20000/Portfolio pull request #1
Opened 2023-06-01 15:42 UTC by Rdzaman20000

Added linters

2023-06-02 13:22 UTC, frank1738 reviewed
Hi @Rdzaman20000 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project with failing linter checks. Kindly fix them are resubmit it

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-02 16:07 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Rdzaman20000   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Following the GitHub flow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

- [ ] Based on my review of your project, it appears that the current design is optimized for desktop view. However, as per the project requirements, it is necessary to adapt the project to be more mobile-friendly.

- I suggest making adjustments to the project's design and layout to ensure it is responsive and compatible with mobile devices. This includes optimizing the sizing, spacing, and positioning of elements to provide a better user experience on smaller screens. By prioritizing mobile responsiveness, you will align the project with the desired specifications and enhance its overall usability.

- [ ] To adapt your project to a mobile view, you can follow these steps:

- Adjust CSS Styles: Modify the CSS styles to ensure that the layout and elements are optimized for smaller screens. This may involve adjusting the widths, heights, margins, and paddings of various elements to fit within the mobile viewport.

- Utilize Media Queries: Implement media queries in your CSS code to target specific screen sizes and apply different styles accordingly. This will allow you to define specific styles for mobile devices, ensuring that your project appears correctly on different screen sizes.

- Test Responsiveness: To view the mobile version of your project using the Google Chrome browser, you can utilize the built-in developer tools. Open your project in Chrome, right-click on the page, and select "Inspect" from the context menu. This will open the Chrome DevTools panel. At the top-left corner of the panel, you will find a device toggle icon (usually shaped like a mobile phone and a tablet). Click on it to switch to the mobile view. You can also choose specific device models or define custom viewport sizes to test how your project responds to different mobile screen sizes.

- Iterate and Refine: Once you have made the necessary changes and viewed the mobile version using Chrome DevTools, assess the responsiveness of your project. Make any additional adjustments as needed to ensure optimal presentation and usability on mobile devices.

- By following these steps, you can successfully adapt your project to a mobile view and test it using the Chrome browser's developer tools. This will help you ensure that your project meets the mobile responsiveness requirements and delivers a seamless user experience on smaller screens.

- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.

- [ ] Your Design on Mobile view

![image](https://github.com/Rdzaman20000/Portfolio/assets/68823331/c63f8624-ef99-41f2-9655-e87c80bee7fe)

- [ ] Your Design on Desktop view

- which is not the size you are required to build now

![image](https://github.com/Rdzaman20000/Portfolio/assets/68823331/72a94c81-12f4-4600-a159-f8f573cf8117)



- [ ] Microverse Figma Design Mobile View

- Which you are required to build now for responsiveness 

![image](https://github.com/Rdzaman20000/Portfolio/assets/68823331/68c54b7e-fb6b-4dd2-a37b-c3506183507e)


# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +  <br/>
- [ ] I kindly suggest that you remove this image logo or you  replace it with your own custom logo

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +**[My_Portfolio]** is a webpage made with html and css
- [x] Great job on adding a project summary! However, I suggest you provide more details about the project to ensure that people can gain a thorough understanding of it.

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +html,css
- [x] I recommend refining the CSS to enhance professionalism.

```
<details>
HTML
CSS
</details>
```

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +
- [x] I suggest editing this section with the following content to enhance the professionalism of your README.
```

In order to run this project you need:

- You need to have NodeJS installed
- A Web Browser Google Chrome, Firefox, etc
- A Code Edit
- or VSCode, Atom etc 
``

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +
- [x] I suggest editing this section with the following content  as the current link has some typo errors to enhance the professionalism of your README.

`git@github.com:Rdzaman20000/Portfolio.git`

2023-06-02 16:07 UTC, Cabraham1 commented on README.md
> +
- [x] Please replace the placeholder for issues with the link to your repository's actual issues page.

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +    </div>
- [x] Based on the project requirements, I kindly suggest wrapping this section within a `<header>` tag. This will ensure that the section is appropriately marked up according to the specified guidelines.

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +      <div class="logo"><img src="images/My Logo.png" alt="" /></div>
- [x] I kindly suggest adding an `<a>` tag to your logo to create an anchor tag. This will allow users to click on the logo and potentially navigate to a specific destination or webpage.

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +      <div class="menu"><img src="images/Union.png" alt="" /></div>
- [x] I recommend wrapping your hamburger menu within a `<nav>` tag or using appropriate semantic markup. This will ensure proper structure and enhance accessibility for screen readers and other assistive technologies. Additionally, consider placing the hamburger menu on the right side for better convention and user experience on mobile devices.

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +    </div>
- [x] I highly recommend wrapping your content inside a `<section>` not a div element that you are currently using now. The `<section>` tag represents a generic standalone section of the document. By using this tag, you can enhance the structure and organization of your content. 👍🏿

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +      </div>
- [x] I highly recommend adding the background using CSS background-image property instead of directly inserting the image in the HTML file. This approach separates the presentation from the structure, making it easier to manage and update. Remove the image from the HTML file and utilize CSS to apply the background image for better maintainability.

2023-06-02 16:07 UTC, Cabraham1 commented on index.html
> +          </div>
- [x] I would like to suggest a change to the structure of the code. Instead of using a <div> element to group the icons, I recommend using a <ul> (unordered list) element and placing each icon within an <li> (list item) element.

By implementing this change, you will achieve a more semantically correct structure for your social media icons. Additionally, it will provide better accessibility and easier maintenance in the future.

- [ ] please make sure to include the <a> tags around the social media links in your code. This will allow users to click on the icons and navigate to the respective social media profiles.

- [ ] Additionally, I noticed that the layout and design of your social icons do not match the Figma design. To rectify this, you may need to modify the HTML and CSS to ensure that the icons are displayed correctly, following the intended layout and design specified in the Figma design.

- [ ] Your design

![image](https://github.com/Rdzaman20000/Portfolio/assets/68823331/cf1d8294-d049-4007-b868-0ae4f3a714b9)

- [ ] Figma Design

![image](https://github.com/Rdzaman20000/Portfolio/assets/68823331/2bae2674-84fa-4bd4-a2ff-d34d4eecccb3)

2023-06-05 17:24 UTC, Rdzaman20000 commented
- Add main HTML and CSS files
- Modify the readme file
- Modify the mobile and desktop version

2023-06-06 00:01 UTC, Kossi-stack requested changes
## Hi @Rdzaman20000,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️


 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-06 00:01 UTC, Kossi-stack commented on index.html
> +      <section class="logo"><a href="#">My Logo</a></section>
- [x] Kindly make sure to use the `a` tag then remove the section.
- This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-06-06 00:01 UTC, Kossi-stack commented on index.html
> +      <section class="nav_bar_contents">
- [ ] kindly make sure to use the `nav` tag then  remove the section. both `a` tag and `nav` tag will be in the `header` tag
- The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-06-06 00:01 UTC, Kossi-stack commented on index.html
> +        <h2>I'm a Software Developer</h2>
- [ ] Kindly make sure to use `h1` for the main title.
- If you want that google (and other search engines) knows about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.If you want that google (and other search engines) knows about a specific topic, in this case, you, use an h1 tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-06-06 00:01 UTC, Kossi-stack commented on index.html
> +      <ul id="sm">
- [ ] Kindly put the list of icons using a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-06-06 08:26 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @Rdzaman20000 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Correct use of HTML tags for semantic reasons ✔️ 
- The designs follows the Figma design ✔️ 
- Well-structured files :heavy_check_mark: 


Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- [ ] Please ensure that you consider using a descriptive branch name like `create_comments`, `portifolio-setup` ☺️.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-06-06 08:28 UTC, merged